
// Objective-C API for talking to the following Go packages
//
//	github.com/minvws/nl-covid19-coronatester-ctcl-core/clmobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ctcl_FRAMEWORK_H__
#define __Ctcl_FRAMEWORK_H__

#include "Clmobile.objc.h"
#include "Universe.objc.h"

#endif
