
// Objective-C API for talking to the following Go packages
//
//	gitlab.com/confiks/ctcl/holder/jsoninterface
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ctcl_FRAMEWORK_H__
#define __Ctcl_FRAMEWORK_H__

#include "Jsoninterface.objc.h"
#include "Universe.objc.h"

#endif
