// Objective-C API for talking to gitlab.com/confiks/ctcl/holder/jsoninterface Go package.
//   gobind -lang=objc gitlab.com/confiks/ctcl/holder/jsoninterface
//
// File is generated by gobind. Do not edit.

#ifndef __Jsoninterface_H__
#define __Jsoninterface_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSData* _Nullable JsoninterfaceCreateCommitmentMessage(NSData* _Nullable cmmMsgJson);

FOUNDATION_EXPORT NSData* _Nullable JsoninterfaceCreateCredential(NSData* _Nullable credMsgJson);

FOUNDATION_EXPORT NSData* _Nullable JsoninterfaceGenerateHolderSk(void);

#endif
