/*
* Copyright (c) 2021 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
*  Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
*
*  SPDX-License-Identifier: EUPL-1.2
*/

@testable import CTR
import XCTest
import Nimble

class OpenSSLTests: XCTestCase {

	var sut = OpenSSL()
	let testBundle = Bundle(for: OpenSSLTests.self)

	override func setUp() {

		super.setUp()
		sut = OpenSSL()
	}

	// Find authorityKey with po print_octed_as_hex(authorityKeyIdentifier)

	let authorityKeyIdentifier = Data([0x04, 0x14, /* keyID starts here: */ 0x27, 0xec, 0x20, 0xfd, 0x74, 0xbc, 0x41, 0xc5, 0xa7, 0x4d, 0x29, 0x69, 0x62, 0xe6, 0xd8, 0xea, 0x5d, 0x82, 0x64, 0x05])

	let deepAuthorityKeyIdentifier = Data([0x04, 0x14, /* keyID starts here: */ 0xa7, 0x8d, 0x20, 0x24, 0xa1, 0xfe, 0x47, 0x55, 0x6e, 0x2a, 0xb5, 0xed, 0x64, 0x20, 0x32, 0x48, 0xbb, 0x1c, 0xf4, 0x45])

	let noCommonNameAuthorityKeyIdentifier = Data([0x04, 0x14, /* keyID starts here: */ 0x43, 0x84, 0x4c, 0xb7, 0x6c, 0xb1, 0x22, 0x7e, 0x28, 0xb0, 0x2c, 0x27, 0xbf, 0xab, 0x20, 0xd6, 0x6f, 0x53, 0xba, 0x80 ])

	let payload = Data(base64Encoded: "WwogeyJhZm5hbWVkYXR1bSI6IjIwMjAtMDYtMTdUMTA6MDA6MDAuMDAwKzAyMDAiLAogICJ1aXRzbGFnZGF0dW0iOiIyMDIwLTA2LTE3VDEwOjEwOjAwLjAwMCswMjAwIiwKICAicmVzdWx0YWF0IjoiTkVHQVRJRUYiLAogICJhZnNwcmFha1N0YXR1cyI6IkFGR0VST05EIiwKICAiYWZzcHJhYWtJZCI6Mjc4NzE3Njh9LAogeyJhZm5hbWVkYXR1bSI6IjIwMjAtMTEtMDhUMTA6MTU6MDAuMDAwKzAxMDAiLAogICAidWl0c2xhZ2RhdHVtIjoiMjAyMC0xMS0wOVQwNzo1MDozOS4wMDArMDEwMCIsCiAgICJyZXN1bHRhYXQiOiJQT1NJVElFRiIsCiAgICJhZnNwcmFha1N0YXR1cyI6IkFGR0VST05EIiwKICAgImFmc3ByYWFrSWQiOjI1ODcxOTcyMTl9Cl0K" )!

	let wrongPayload = Data(base64Encoded: "WwogeyJhZm5hbWVkYXR1bSI6IjIwMjAtMDYtMTdUMTA6MDA6MDAuMDAwKzAyMDAiLAogICJ1aXRzbGFnZGF0dW0iOiIyMDIwLTA2LTE3VDEwOjEwOjAwLjAwMCswMjAwIiwKICAicmVzdWx0YWF0IjoiTkVHQVRJRUYiLAogICJhZnNwcmFha1N0YXR1cyI6IkFGR0VST05EIiwKICAiYWZzcHJhYWtJZCI6Mjc4NzE3Njh9LAogeyJhZm5hbWVkYXR1bSI6IjIwMjAtMTEtMDhUMTA6MTU6MDAuMDAwKzAxMDAiLAogICAidWl0c2xhZ2RhdHVtIjoiMjAyMC0xMS0wOVQwNzo1MDozOS4wMDArMDEwMCIsCiAgICJyZXN1bHRhYXQiOiJQT1NJVElFRiIsCiAgICJhZnNwcmFha1N0YXR1cyI6IkFGR0VST05EIiwKICAgImFmc3ByYWFrSWQiOjI1ODcxOTcyMTl9Cl1K" )!

	// Use sign.sh to generate this signature (rsa_padding_mode: pkcs1)
	let signaturePKCS = Data(base64Encoded: "MIIKcAYJKoZIhvcNAQcCoIIKYTCCCl0CAQExDTALBglghkgBZQMEAgEwCwYJKoZIhvcNAQcBoIIHsDCCA5owggKCoAMCAQICAgPyMA0GCSqGSIb3DQEBCwUAMFoxKzApBgNVBAMMIlN0YWF0IGRlciBOZWRlcmxhbmRlbiBSb290IENBIC0gRzMxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjELMAkGA1UEBhMCTkwwHhcNMjExMjE3MTIzNTM0WhcNMjIwMTE2MTIzNTM0WjBnMQswCQYDVQQGEwJOTDEeMBwGA1UECgwVU3RhYXQgZGVyIE5lZGVybGFuZGVuMTgwNgYDVQQDDC9TdGFhdCBkZXIgTmVkZXJsYW5kZW4gT3JnYW5pc2F0aWUgLSBTZXJ2aWNlcyBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALtp/Rke2wh+o6UOO9R0TYz+eti4eJAa6omVCuR/Ilzx6CnfwRowXRF9GXTDkCQNcu67OAptLBkBXf7TL07vBfIM+dvPvocdySmZv37bz8/tU/SXsjCGVuA00VGR9aV6ru+3nbkxT6gHjMh8y5QYGxOz65cQh9h+KfqIB9G5JmmhAN81Vns7zkbPZK/XekNjJQ0ooKPljccZBuWJJm5gOOUxzJrfYqc/1vTFE8eKZ0+I6LHBfaWuXp/O/2sbBqvCCxDNJm0e/y8pmSbfu/jNnKrQJMmVF7MonxvrrLi2hUmkidDX3pmAGGyJdYzuoxd9abXoUri1HlqGbzXpRlmQFrECAwEAAaNdMFswCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBQn7CD9dLxBxadNKWli5tjqXYJkBTAfBgNVHSMEGDAWgBS3vo02rNqdsk0lw09dIdXOl+bFmTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCE7353r5hM7OD6b+MKWNVH95fACxfZIXf4/3MA4ZBELbv4n1lTQyWT3RMJTkpknoPdblwISPpUuU5oLxTh6rnU1K3mvTSHhMcFav5HSkYxoNdyXu1DJCJQenhItuRKK3wb+6KyKslq5l426E22mWRDGkkS3yZjfpJYny2MBAm+jmAJkAiVkMiO/4kbLUYVeh6TDZ7SSFQJ2NMhwzqf3tuh6CTbsCjHCky+rozN6Z7ijtP0R7gqzxv+4P5zqa/mUth6FysSqB51tN8Tc50kQoCjzHmGL249biMXcrEVKICWBZPcSBIQyCeFc27fJ3eCZK+Kf8SrcGAAg84K+/2IBgf5MIIEDjCCAvagAwIBAgILAN6tvu/erb7vwN4wDQYJKoZIhvcNAQELBQAwZzELMAkGA1UEBhMCTkwxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjE4MDYGA1UEAwwvU3RhYXQgZGVyIE5lZGVybGFuZGVuIE9yZ2FuaXNhdGllIC0gU2VydmljZXMgRzMwHhcNMjExMjE3MTIzNTM0WhcNMjIxMjE3MTIzNTM0WjB9MQswCQYDVQQGEwJOTDE5MDcGA1UECgwwTWluaXN0ZXJpZSB2YW4gVm9sa3NnZXpvbmRoZWlkLCBXZWx6aWpuIGVuIFNwb3J0MRgwFgYDVQQLDA9Db3JvbmEgQWxlcnRlcnMxGTAXBgNVBAMMEC5jb3JvbmF0ZXN0ZXIubmwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVphG8aLLtePbrrHp14IBavBhEBg5OSXWw7vQg8ICQLjzy14bNYbzMcSNht9nRbK/esAGqDQnA73NvBeDrbTte9s3efToNXJtCcAUNmb4w0oNHXpUxnq/gxdJXj/dWB8n4Jp6UM4HaOCtP6SvyF35iM4+ykolJ3YF8SttXCl/cg4TFwz/FoHXXL4WxrWK4+mCE1IqQazhbamSGk5kmWKaeycef+k/9pDay0SGvYP3cqjXVVJDWKffj3OqX1Cfv0whtlnGdLoZzt2YuXF12mYiaszOP+Zaem/bXdig2WGh3gg+uZxlGtWlxBkzy9C9jf7YYSjnvtxe53ZjVUkpTFT2fAgMBAAGjgaQwgaEwRwYJYIZIAYb4QgENBDoWOEZvciB0ZXN0aW5nIG9ubHkgYW5kIG5vIHRoaXMgaXMgbm90IHRoZSByZWFsIHRoaW5nLiBEdWguMAsGA1UdDwQEAwIF4DAdBgNVHQ4EFgQUjnXXWIOrxmufQbvu7krsL5XuhqwwHwYDVR0jBBgwFoAUJ+wg/XS8QcWnTSlpYubY6l2CZAUwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEABgWxQAKzdxCDAbguXXvnh3NhE5hwIabz4sFVxBGB8bdg2V/jH5v+BXaB1kdREawFXjwx15BUkpxsGmaqqVuzdnV4QjVFoWk/Oe0Vx38iQkE/hn/+GV8ZWiXOysQ8ETg8vVUhEK47DbR7Cqyt20LtoxOExqw/YeAqizsew6qf0a2GUHlh5+cCaL8QV9XhPbJDPfa8rBWdg9pVEYfiOQ8Sy9fTZsEvYZlyLjUz0YImR1yNwAE5yHF/XAAlnaqjRFlthL7qk6OBOS/MYs4LCRPDkQqQ9cvkwseAJaZmGrXtlTvSPf77dbpw7znmdB01BjnoKxRGZxxUlQdt+lZX7sTgpTGCAoYwggKCAgEBMHYwZzELMAkGA1UEBhMCTkwxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjE4MDYGA1UEAwwvU3RhYXQgZGVyIE5lZGVybGFuZGVuIE9yZ2FuaXNhdGllIC0gU2VydmljZXMgRzMCCwDerb7v3q2+78DeMAsGCWCGSAFlAwQCAaCB5DAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTEyMTcxMjQwMDJaMC8GCSqGSIb3DQEJBDEiBCCN6iJ4JdABvoUbWZ6h6jPmAineuLcsweVEsauDrJpRTTB5BgkqhkiG9w0BCQ8xbDBqMAsGCWCGSAFlAwQBKjALBglghkgBZQMEARYwCwYJYIZIAWUDBAECMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDANBgkqhkiG9w0BAQEFAASCAQAUetOxY6omnjM9ZLLQD62XrKAp+x5UHotA3GPkWzbS2ptkiKLN631Wa4/2CU5TbcgbX2IlI3tOGA1dpnqBxQsB1FliQM9Hy+V6ooh0igPUzYuzrFg6K2IFrPANkJYCPQdYxqBhExeXafu8FMOyJRvVI2nsrXWotZVhcDdVfCfDVvRG5F3NGAkrFWnjOHFwjZBblk5ExeD+6MKXF5EFuMjXzBU5mqCa+s85A3Eqkl0QS3S6dJkqO6yC9yN8exasryU7OWiEQZHqJprTkGKOsHLXGiyhZCF16YJwyh7KbOcyDtZ5d1BUCt01kHTFkeW1CJRghRlO6PTrlKP19CGP6Adh")!

	// Use sign.sh to generate this signature (rsa_padding_mode: pss)
	let signaturePSS = Data(base64Encoded: "MIIKoQYJKoZIhvcNAQcCoIIKkjCCCo4CAQExDTALBglghkgBZQMEAgEwCwYJKoZIhvcNAQcBoIIHsDCCA5owggKCoAMCAQICAgPyMA0GCSqGSIb3DQEBCwUAMFoxKzApBgNVBAMMIlN0YWF0IGRlciBOZWRlcmxhbmRlbiBSb290IENBIC0gRzMxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjELMAkGA1UEBhMCTkwwHhcNMjExMjE3MTIzNTM0WhcNMjIwMTE2MTIzNTM0WjBnMQswCQYDVQQGEwJOTDEeMBwGA1UECgwVU3RhYXQgZGVyIE5lZGVybGFuZGVuMTgwNgYDVQQDDC9TdGFhdCBkZXIgTmVkZXJsYW5kZW4gT3JnYW5pc2F0aWUgLSBTZXJ2aWNlcyBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALtp/Rke2wh+o6UOO9R0TYz+eti4eJAa6omVCuR/Ilzx6CnfwRowXRF9GXTDkCQNcu67OAptLBkBXf7TL07vBfIM+dvPvocdySmZv37bz8/tU/SXsjCGVuA00VGR9aV6ru+3nbkxT6gHjMh8y5QYGxOz65cQh9h+KfqIB9G5JmmhAN81Vns7zkbPZK/XekNjJQ0ooKPljccZBuWJJm5gOOUxzJrfYqc/1vTFE8eKZ0+I6LHBfaWuXp/O/2sbBqvCCxDNJm0e/y8pmSbfu/jNnKrQJMmVF7MonxvrrLi2hUmkidDX3pmAGGyJdYzuoxd9abXoUri1HlqGbzXpRlmQFrECAwEAAaNdMFswCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBQn7CD9dLxBxadNKWli5tjqXYJkBTAfBgNVHSMEGDAWgBS3vo02rNqdsk0lw09dIdXOl+bFmTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCE7353r5hM7OD6b+MKWNVH95fACxfZIXf4/3MA4ZBELbv4n1lTQyWT3RMJTkpknoPdblwISPpUuU5oLxTh6rnU1K3mvTSHhMcFav5HSkYxoNdyXu1DJCJQenhItuRKK3wb+6KyKslq5l426E22mWRDGkkS3yZjfpJYny2MBAm+jmAJkAiVkMiO/4kbLUYVeh6TDZ7SSFQJ2NMhwzqf3tuh6CTbsCjHCky+rozN6Z7ijtP0R7gqzxv+4P5zqa/mUth6FysSqB51tN8Tc50kQoCjzHmGL249biMXcrEVKICWBZPcSBIQyCeFc27fJ3eCZK+Kf8SrcGAAg84K+/2IBgf5MIIEDjCCAvagAwIBAgILAN6tvu/erb7vwN4wDQYJKoZIhvcNAQELBQAwZzELMAkGA1UEBhMCTkwxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjE4MDYGA1UEAwwvU3RhYXQgZGVyIE5lZGVybGFuZGVuIE9yZ2FuaXNhdGllIC0gU2VydmljZXMgRzMwHhcNMjExMjE3MTIzNTM0WhcNMjIxMjE3MTIzNTM0WjB9MQswCQYDVQQGEwJOTDE5MDcGA1UECgwwTWluaXN0ZXJpZSB2YW4gVm9sa3NnZXpvbmRoZWlkLCBXZWx6aWpuIGVuIFNwb3J0MRgwFgYDVQQLDA9Db3JvbmEgQWxlcnRlcnMxGTAXBgNVBAMMEC5jb3JvbmF0ZXN0ZXIubmwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDVphG8aLLtePbrrHp14IBavBhEBg5OSXWw7vQg8ICQLjzy14bNYbzMcSNht9nRbK/esAGqDQnA73NvBeDrbTte9s3efToNXJtCcAUNmb4w0oNHXpUxnq/gxdJXj/dWB8n4Jp6UM4HaOCtP6SvyF35iM4+ykolJ3YF8SttXCl/cg4TFwz/FoHXXL4WxrWK4+mCE1IqQazhbamSGk5kmWKaeycef+k/9pDay0SGvYP3cqjXVVJDWKffj3OqX1Cfv0whtlnGdLoZzt2YuXF12mYiaszOP+Zaem/bXdig2WGh3gg+uZxlGtWlxBkzy9C9jf7YYSjnvtxe53ZjVUkpTFT2fAgMBAAGjgaQwgaEwRwYJYIZIAYb4QgENBDoWOEZvciB0ZXN0aW5nIG9ubHkgYW5kIG5vIHRoaXMgaXMgbm90IHRoZSByZWFsIHRoaW5nLiBEdWguMAsGA1UdDwQEAwIF4DAdBgNVHQ4EFgQUjnXXWIOrxmufQbvu7krsL5XuhqwwHwYDVR0jBBgwFoAUJ+wg/XS8QcWnTSlpYubY6l2CZAUwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEABgWxQAKzdxCDAbguXXvnh3NhE5hwIabz4sFVxBGB8bdg2V/jH5v+BXaB1kdREawFXjwx15BUkpxsGmaqqVuzdnV4QjVFoWk/Oe0Vx38iQkE/hn/+GV8ZWiXOysQ8ETg8vVUhEK47DbR7Cqyt20LtoxOExqw/YeAqizsew6qf0a2GUHlh5+cCaL8QV9XhPbJDPfa8rBWdg9pVEYfiOQ8Sy9fTZsEvYZlyLjUz0YImR1yNwAE5yHF/XAAlnaqjRFlthL7qk6OBOS/MYs4LCRPDkQqQ9cvkwseAJaZmGrXtlTvSPf77dbpw7znmdB01BjnoKxRGZxxUlQdt+lZX7sTgpTGCArcwggKzAgEBMHYwZzELMAkGA1UEBhMCTkwxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjE4MDYGA1UEAwwvU3RhYXQgZGVyIE5lZGVybGFuZGVuIE9yZ2FuaXNhdGllIC0gU2VydmljZXMgRzMCCwDerb7v3q2+78DeMAsGCWCGSAFlAwQCAaCB5DAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yMTEyMTcxMjQzMTVaMC8GCSqGSIb3DQEJBDEiBCCN6iJ4JdABvoUbWZ6h6jPmAineuLcsweVEsauDrJpRTTB5BgkqhkiG9w0BCQ8xbDBqMAsGCWCGSAFlAwQBKjALBglghkgBZQMEARYwCwYJYIZIAWUDBAECMAoGCCqGSIb3DQMHMA4GCCqGSIb3DQMCAgIAgDANBggqhkiG9w0DAgIBQDAHBgUrDgMCBzANBggqhkiG9w0DAgIBKDA+BgkqhkiG9w0BAQowMaANMAsGCWCGSAFlAwQCAaEaMBgGCSqGSIb3DQEBCDALBglghkgBZQMEAgGiBAICAN4EggEAvC1SH8mqstpVSTH5/9nfQ5lPlFTxVW3fzDymQOAzzH3GkYHHtW47akgPGd4fz2Mm82UADpRTUiY67CRwqPGGVysIfqyiskGXiqOHwQHJ5m47Yaolv7mqUWZ8rhesD1vf1X3XXNKQ53PAzxgmVn9N30QkwkQh+KSJdgz4qWtr8bqrmYzdnCotihr71zUXhMq2ifuXPERgb+1LqmCVzEhLeZ6U7uPQyqFx1rYnXYy8+pW1TTMULr9rJHaqEQqEnzTTC1ln88ryzlR82ZyxL6ZFcs5XxhxsHSUe4Ya9wu4EDmFwmyDhcAeX+1Rhd9pa2kMlmYXUJN/UKLTNYq9g2I42Tg==")!

	let signatureNoCommonName = Data(base64Encoded: "MIIJmQYJKoZIhvcNAQcCoIIJijCCCYYCAQExDTALBglghkgBZQMEAgEwCwYJKoZIhvcNAQcBoIIG2TCCA0AwggIooAMCAQICAgPyMA0GCSqGSIb3DQEBCwUAMAAwHhcNMjEwODA2MTIzNDM2WhcNMjEwOTA1MTIzNDM2WjBnMQswCQYDVQQGEwJOTDEeMBwGA1UECgwVU3RhYXQgZGVyIE5lZGVybGFuZGVuMTgwNgYDVQQDDC9TdGFhdCBkZXIgTmVkZXJsYW5kZW4gT3JnYW5pc2F0aWUgLSBTZXJ2aWNlcyBHMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM0yZRNQrplxTCl8xP7c7klRor9VjKlFuOTpKVnzjYK1r2vhxiLS3MFUyigClpTvhE71lrSuT51w5NdhHwgx+nzqCCnPsKacPyIFPdbgDsuDhSOI61TabwjWP21NZJimf0sdaFW+3KpAOY300m9MwpwwTQJzg/okU4LRp8UDNbYkbqAgXH/TCrmSMnJPFAIlVeI8eTOWV5KOh3wSljCnx734J7pK3Pf6DzPhNNb6mPkCVrnbwUli8WdNZS1l5do6iNe9kpgH7X6Tvrf4hBUl+w9ED5P/O6Yqirinsf/v9bRri9tGlL7cRUIw2wkVeMpxpkubuhBHdXTiYyFXxvyp+VECAwEAAaNdMFswCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBRDhEy3bLEifiiwLCe/qyDWb1O6gDAfBgNVHSMEGDAWgBQfa8EPH1d4UdtFvSBY87R34Pz1zTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA9+aZHyMiL7pMn3PnvlwbnpbRgKY4fXXjZ70bm1/TSzL5va0yZ00r70SzWO8ZjyLHckU55Uu1XiQNuwgpW6t8VxzhLKPh9Dxbusopx6vBBtQJBJs0hx44MYvcg4vGUSE9vSpZKGtzkijgx4ZSu/XqmLHWsGg/hFoRWMV6CZI7CpnwQlwRei+DvOnvZeACLUPYZZPVTqFSnWsh1GsKqrzHoz30GzeAHrFjiLS/i/t/qzJydSaZjvTqFSUzcmYhQiXCYELtgutpe+ZzZSNgeoWbSJOsxuBD3Pn7QrzaRxStpCvpCIutYHPd4Sbhm1kGPfz4vgTDPLMYiPemRYySUH/3OMIIDkTCCAnmgAwIBAgILAN6tvu/erb7vwN4wDQYJKoZIhvcNAQELBQAwZzELMAkGA1UEBhMCTkwxHjAcBgNVBAoMFVN0YWF0IGRlciBOZWRlcmxhbmRlbjE4MDYGA1UEAwwvU3RhYXQgZGVyIE5lZGVybGFuZGVuIE9yZ2FuaXNhdGllIC0gU2VydmljZXMgRzMwHhcNMjEwODA2MTIzNDM2WhcNMjEwOTA1MTIzNDM2WjAAMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA09dpRRFqAEr9pgXncnGXT7dkG1fSHLkkcZzPLq5cLKGd7DaoSb/TVTn6lWJKdPV+4dUfCexWKu4usBnbq11wg+Laau2++xX0jVIhm6BQ2NUS7Va4HBogDM6b365fPo6Xk7wrgvA73DX518LrG7rsgBWaP3he8z24W9oJR/89MChJpAD4sOja78C+fJX4+zrmaactNvVkfeKfxBP98dvW4+131i6cwcqdcYDntz+tQ+XofrDFUgClzkaw2kKyt+SpAXjZmbKkXI2Y02EHNJIZVQl/knBHaItzx+JI3EsnSPm0f/kVsK+XeT+vdMqgGbol63C86xTwMUuhBgkxdykJVQIDAQABo4GkMIGhMEcGCWCGSAGG+EIBDQQ6FjhGb3IgdGVzdGluZyBvbmx5IGFuZCBubyB0aGlzIGlzIG5vdCB0aGUgcmVhbCB0aGluZy4gRHVoLjALBgNVHQ8EBAMCBeAwHQYDVR0OBBYEFLjbvlSXwKhaSCSg44vH8/cZE9ZqMB8GA1UdIwQYMBaAFEOETLdssSJ+KLAsJ7+rINZvU7qAMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAD/re6fHIfIDzH3TmgRyrp1uzVvSB8EskSel8+DJMmaFIvnQmiLPB3SSRIBsbE28Pj2Yqb7JAkNVbEisQpMtd1b8C1r3hifUOO+uqboqhzsiHlaeHwkUBj6KZIi3NNhO5+C1tJn/6XSzNQcPXsGx2gd759ky/MIiySFESW2blQHlX8oEDRi0NrM+SRZoTwiIl7Obhzvb81XzU0FI64dqUffka+s6vdipt3m+QmGf13BSLsOGhi9RnzEo2atN0Ynl63ESCpALTJr+X/XDUx8I8xIn5OiLc+upbJSBGSQPIyT62sv3y8ZxLtGghUCDBqgRDdjSc+8WAYHncWrB4qcKYaIxggKGMIICggIBATB2MGcxCzAJBgNVBAYTAk5MMR4wHAYDVQQKDBVTdGFhdCBkZXIgTmVkZXJsYW5kZW4xODA2BgNVBAMML1N0YWF0IGRlciBOZWRlcmxhbmRlbiBPcmdhbmlzYXRpZSAtIFNlcnZpY2VzIEczAgsA3q2+796tvu/A3jALBglghkgBZQMEAgGggeQwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjEwODA2MTIzNDQyWjAvBgkqhkiG9w0BCQQxIgQgjeoieCXQAb6FG1meoeoz5gIp3ri3LMHlRLGrg6yaUU0weQYJKoZIhvcNAQkPMWwwajALBglghkgBZQMEASowCwYJYIZIAWUDBAEWMAsGCWCGSAFlAwQBAjAKBggqhkiG9w0DBzAOBggqhkiG9w0DAgICAIAwDQYIKoZIhvcNAwICAUAwBwYFKw4DAgcwDQYIKoZIhvcNAwICASgwDQYJKoZIhvcNAQEBBQAEggEAeHdsCJXHkaRh4LkVAUMAieWUU/DsQRlRJnQuhTRVqaGCY1+n8/5ImjS8HtBOL+GM08dxfACOtGPo777WEYQjtEHoUPaX7/PnCsIRSX+xKFOsz8sRH1xglyARfuEYBGk55kohPEh/oqyarNbQUYebaCUAw6r5OiMnC8M5Gi4HK2oKGPzyFhzdBt7MLj0PT9dTjVOFxh3qUH/Wm+sIW2BMOk/OUV9JrH0yJqpT80zL5aGNJ8/AKMk2e3upOrefJrDrT2v82Ro3O1iSgBfdEdk4Q7LVd20rN6ihy19ebJQ8j48nLWd6dZlqLWI8R9hVEHipYKg+evzqq5DYkt2OFyomBg==")!

	// use long-chain.sh to generate this signature
	let deepSignature = Data(base64Encoded: "MIImfgYJKoZIhvcNAQcCoIImbzCCJmsCAQExDTALBglghkgBZQMEAgEwCwYJKoZIhvcNAQcBoIIj4zCCAvswggHjoAMCAQICFGCNViERDfNyDzbJsB3DP2nvB8qcMA0GCSqGSIb3DQEBCwUAMA0xCzAJBgNVBAMMAkNBMB4XDTIxMTExNzEyMTEyNVoXDTIyMTExNzEyMTEyNVowDTELMAkGA1UEAwwCQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtBTu/oAdkVBzsLo7xCbSXu0K8yUNNaIHn9p0LE6AFas0Xc5qavW+LguMSaJbiplj7b5DOT0urtPtO7l7DpWg+NYVIWsUeTkHs+mU8VP1ZdswINTJMOoq87gAsRZ2snzOU7Jf/W6e4UIIWqpqeZwjkvRCjxP9KitF6FRU0KaGd8RwHa6pu/NoAZjmWd6fGQbem12azztSYLUzglgKmvTCEWhiDh13VW0JpUuB2e1+uRLJS6Zpkp/WifzNj0p7H2pcYpAZKNu1B2MQ/peTbRpJOYPu/A3EW7xILNIrwiTKX2S4aiPjzWyjgU35/Ipvlos8rAQbOiC9n2ADrTndTveSpAgMBAAGjUzBRMB0GA1UdDgQWBBSxv7+w2x0Z3BBAyjAmhswTKgyNxjAfBgNVHSMEGDAWgBSxv7+w2x0Z3BBAyjAmhswTKgyNxjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCumxwJ5xJEk5cnCryD/3JPshhKYOt13yfEukeaChge7sFxhG10J8qcvnGapiyFeYfd1Sm2rA1DYVIOh2jslFHz/KSea5RmRu9j4OB1VgUqceAXCTjrl/U/seuvt8RCW+xs4kbec8N4e05oRwzXG3diKcqowclz4lflbFWt3Kb/UooizV9pd3Ht/fnTLC978MGMUsZ2plpZK/9Lv9hK0Ge0woR7Qvb8HDTk+rwSI2HlXkYWuHMKFG6VtObr8f5VWafaJwQU2aK8FnampcmH8wWEzh/VoAh/AZPeY3Pj15EYzhqQfQHJFnDmsAvvh7rbfEgBYeiwnd2YzFH6/A2VdfEgMIIDQjCCAiqgAwIBAgICA+gwDQYJKoZIhvcNAQELBQAwDTELMAkGA1UEAwwCQ0EwHhcNMjExMTE3MTIxMTI1WhcNMjIxMTE3MTIxMTI1WjARMQ8wDQYDVQQDDAYxIGRlZXAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCZb/+JP26szP6OsafHWwjsbIsXXW77bDSQTD8faazf33PrCcoUZYX79D0Ky4MqrVrboNY8KdYV5GM3R65vTSsNc3NmnBAx8mcqO7ial8/bvXayQevykgDKa8OIA7Ku8JqSKcqe5gzNLwuFtDv7vgN8H8IeeGLdAi9WfeglrJz+F+ktSC4joz49u0tMWtoiN1apbjNMal9HmOEbDSksd4MJ4QQmffAQOGfT4+JAyintNBnQs0c3RYhaucAPE3NblJrpOod7taXo5DoKCVCjP02GQw+ef5aYtxeyD34NX/pc/jGd9Mj3nNGYf5Z42Bgtm65TqZwdUL3cwHsqwmQVd0BAgMBAAGjgacwgaQwRwYJYIZIAYb4QgENBDoWOEZvciB0ZXN0aW5nIG9ubHkgYW5kIG5vIHRoaXMgaXMgbm90IHRoZSByZWFsIHRoaW5nLiBEdWguMAsGA1UdDwQEAwIBBjAdBgNVHQ4EFgQUXMVBRjQ0a6na2u3zpIQWMV9EIvYwHwYDVR0jBBgwFoAUsb+/sNsdGdwQQMowJobMEyoMjcYwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEASmD+Dnlz8Ct8NLulOin1bDoK/ZIDe8pbD7WGYtVFaGfUY1jTjh0djEvDqizBqa6p7Lgl7Nqg0blD/xilYv4v5NiJ9WHZuM0UuA2VFYSM+xHTwC+bKrQ7KukhAF0jAFs3HzoojzMTL7tHrt7HcP6q6K+loUaVThKXIQUJ43LiCmAKfz97X3DaH8jMemhGo7XYhs+U4Q6WtSV0u0ENx7Mhtzi3VLK7YXd+0GFVh+l2I8wxn+40aEFbxjntrYpIBreMAdjZxYPa9OcoWZLqJGC8KztKuFlLcnNQ/g0yorN9+r+Vf9RVyCtKX1MBXQq5qBlnDIW9U31hxNPwenqEwZbXwTCCA0YwggIuoAMCAQICAgPoMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMMBjEgZGVlcDAeFw0yMTExMTcxMjExMjZaFw0yMjExMTcxMjExMjZaMBExDzANBgNVBAMMBjIgZGVlcDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO0s/Fiaw9TSw/9Iu7BVQhgBCeXb16kL64Fa/DkCnfYWf8zZ0L2t0tSzSJkgDvpVTqSpoG2OshCJMmNY0we8QRexwmEDfak2jqDEkTE0wYE9yI60ZUZbPfRHo8v0gaLtPe9idAyhAsZqnPQM0SeIvJIDgsmrrCi8UK3Uu2mwkem1KC83n+c+ZxfeRiCboUtfAoBs7TY2ZjD0JnocWTPtRsAn3ETyt8itAd5/kH2Y4QCUFmchpfgTDXQoBLLvsPpArpl8f4sl5lhUeyjHxj5mbf8eyvhoE5QzoyPb11ZLB7ukupywEPZ4N+bmjf/OjIdW6bZRGsJl6dfT6PxcdkUa5MUCAwEAAaOBpzCBpDBHBglghkgBhvhCAQ0EOhY4Rm9yIHRlc3Rpbmcgb25seSBhbmQgbm8gdGhpcyBpcyBub3QgdGhlIHJlYWwgdGhpbmcuIER1aC4wCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBRYJDoD/pEdpOLVETMxojd07NNusDAfBgNVHSMEGDAWgBRcxUFGNDRrqdra7fOkhBYxX0Qi9jAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBV49ceUshfbryphVCbqhGQg0+pkAGjXdlqhOnWLj0ZrUysZG282+akr4DkiZeJtZ0ad0DQ5RXAvlAFOvuoVnthXpwg0sirKjhyMl/waa1PbLuauZ47MrfJ2K8kp9HuLm9+F1UA9Dmo0LBNlg+o1fxgxzT6Lv/lFf9/oCzvsz1KJHc5rIGQ0X/W6ji8qw0Cm4FbNCnEhIj6EsmrSIpBex1uh4+q/2HN001wrgYhcfJuZ1OQ8fg7sLV8u8cbfMOShegduzU+8DboT7i9DkLp85APjko7uPeNlRTeEDIm42VjlQdAsPCy3E3tVppJfy5k//UVx77ivkza+YySr14kP1MfMIIDRjCCAi6gAwIBAgICA+gwDQYJKoZIhvcNAQELBQAwETEPMA0GA1UEAwwGMiBkZWVwMB4XDTIxMTExNzEyMTEyNloXDTIyMTExNzEyMTEyNlowETEPMA0GA1UEAwwGMyBkZWVwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAulJjdzVSJhzFzKF9SxYJhHXcbbgqS4duShtUYw20gW7fa9qzFh/CO3zSyyv5mYxz87cGdnXFL5v+fQP57Okl52LtIakU/JUBlTKHxf8baLM9HGkhta9elxrjuy5m/K1Ul7U5uiBEbjtIUSMlRUbg+g8LZe8cThagxpETyClK8aE5vdqAI5IW3OCsF/QpKqY+kVPdtcPRFi7wr+pOfprD9bv/nqN7TX0oL0qsclvw4pS6nOdFCstG/3/bs+stfk1VOqbDHvlXeaMuIOC1xKMzjgeMwql+LB/N3ivlG9RPk7w8/7Qa9d/bG8j04Suium6DKsOdoKVp2hvAPkmWX6qPPQIDAQABo4GnMIGkMEcGCWCGSAGG+EIBDQQ6FjhGb3IgdGVzdGluZyBvbmx5IGFuZCBubyB0aGlzIGlzIG5vdCB0aGUgcmVhbCB0aGluZy4gRHVoLjALBgNVHQ8EBAMCAQYwHQYDVR0OBBYEFOmtB6++kEi51H0BKFnX24LXyAO4MB8GA1UdIwQYMBaAFFgkOgP+kR2k4tURMzGiN3Ts026wMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAD9qGFvnEQiOmwa+UTlh2HaToWcGPS5IHY1We30uBIbecax2PSU59z2vqw3yFwsWW5kVtmt9xtKPP0gpq1rdWxIz/SYB2CPRPb4Vlbj4M9w8lMYJEJnnkfUGpD8nm65khLfWkWtNZZeNvvH8i3BZVCN9svvEN9Q4moBwBd0D+nXMgXnXPEpFaF+I8RgECrFPHSO8A2UEAlAPCh6A5Iwyo7SlnVxCvn8vDJPt4o4yeO65NBygmPGWFedP5pku87RwHdE8yzs7PbgoJIJ7Ek9KgQsIbiNvWnTHkJIYGmm63s9wBuOw0EB1pM50WlpRkVDrJAZcCC447ZPlRK3X7S8SHoowggNGMIICLqADAgECAgID6DANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAYzIGRlZXAwHhcNMjExMTE3MTIxMTI2WhcNMjIxMTE3MTIxMTI2WjARMQ8wDQYDVQQDDAY0IGRlZXAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC5gFVnGAJ4GIywPX5XIITqv9tINj16UfSaCdBoEpaRKGBBb+hAAnSPrlNvaMjcCZPhSlL1W85ElyzNYtZ1ID0Z8JtaoDUIwBJpHjMMUiO8+xgHxNWMimm47H6wv3eAd4+zXCScKPijLICWuYEjsddcpgFy1W32/z3H3/zx6uGdvan4El8wsbaVGERQVGSit+il0cH+4+sL3wn6UYDG6tNQhcXC/2WAbh0ck3U/gKvq7vGMsOZ9ghcVfZBu4mQGSl+gzOfccDQeKuhiPX35z/EeLunkWpPUvwTyE+a9hXKNPSIp9OC51/ReKHWF6eSQ2IFwciHvNrgbVQvmsn5Sg/wXAgMBAAGjgacwgaQwRwYJYIZIAYb4QgENBDoWOEZvciB0ZXN0aW5nIG9ubHkgYW5kIG5vIHRoaXMgaXMgbm90IHRoZSByZWFsIHRoaW5nLiBEdWguMAsGA1UdDwQEAwIBBjAdBgNVHQ4EFgQUM+W7foJa4PS4zTYkWQifw/wU6gkwHwYDVR0jBBgwFoAU6a0Hr76QSLnUfQEoWdfbgtfIA7gwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAnVRNvRJm4ItAVj7Yy7OgIgT2+QJEk+F0vPp7WrSVQOkwROUicaKXzOnO9/rzcr3V/0vit92GGbhr87xvR3iGPch8/8R4ENrpImXd3VvqxwupTOUkLaesOkZWU2ZH7Mr0KLGTjlOp31ure5byeXV6zFsO6rGVXenuumcgdQyKVAm/0Pib+6DaP94ecx/WLBLtdRk8mzvRHA9dbFjvs/zWc6e6kE7nGkmW5xek3Toe8IDkj2lmzXHIXuPPcOfG0OQgHX7P9nHUOM/+4JtzFAeZ2ZZ+mNtEElaiA0MSDrUatsbfLqGwtDI6shklYVKGet9q3kbLwYwqpBz5C0tMlVabrjCCA0YwggIuoAMCAQICAgPoMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMMBjQgZGVlcDAeFw0yMTExMTcxMjExMjZaFw0yMjExMTcxMjExMjZaMBExDzANBgNVBAMMBjUgZGVlcDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALcS+eJAP5m8tAWiuQ5TGeGT+gLSzYrQAw9yEs4IVqsJ7o4UqKNnqGrM+a7aFcOKaILRS8E4B1R07p2Fmq5uA8xZjiXbdSeNHbP8Eo9MhbH+wkL2HRmrzacQqpmXh+BOhniIPX9DCcvKBiFCjYW0sT8D8N0jdV+f5c9K4UOa0T2jT3+6jYkEIHsc2SDng4rvmV3yOH4zDhMkzbXSOk91txOyt6k27dPRY3y8wS6wo/lxuMqYvdBDUax+FPvxgnZM8fMiW9APpof066QW2UTFYGGwKHlD670fopxobOKLKzGHLxixVjbL6CCbTACma6T00ej5ewXI6Qnlf9cRF2uQu3sCAwEAAaOBpzCBpDBHBglghkgBhvhCAQ0EOhY4Rm9yIHRlc3Rpbmcgb25seSBhbmQgbm8gdGhpcyBpcyBub3QgdGhlIHJlYWwgdGhpbmcuIER1aC4wCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBQnG6kUzVWhaRR+/JJgsHKFwj2cbDAfBgNVHSMEGDAWgBQz5bt+glrg9LjNNiRZCJ/D/BTqCTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBdUzwgvdyDIhi0JDTh03r6Xv2d8mCQcAKoTgTvyUm+v0NdQmYiXihKrItQTlnJM5Ljf7nwe18ZueudOdcxbGInIeTdX1D6AucT2b9cihXOn3i1T65kmLgAO7Pcg1ghIdYo3P3B03cyiuspPD+f9nYUxn032LmBDZHbwyJoeviA4OQRNIkWfxE902+FPNeHq6ZccRJ6mWrtuvSpQRaukS6fySQLWfPQ3YHu4O5uTIMx9swoHrkXmaMiJNVwAKxM6oKAyKCd1STQIR/1jUGmo5BtF5AX4Jw5pfs3TvoAoFZMqfYNDzm/0TD+t6A6446qMVjYHaFz9l+tF5VzLgIMz421MIIDRjCCAi6gAwIBAgICA+gwDQYJKoZIhvcNAQELBQAwETEPMA0GA1UEAwwGNSBkZWVwMB4XDTIxMTExNzEyMTEyNloXDTIyMTExNzEyMTEyNlowETEPMA0GA1UEAwwGNiBkZWVwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzI77UMkuaxbe7fYtj6Aylf0YW5j+pp4bp91RJXkLcPReZwzDWTAs7smAd9CJgVPTMT0tkZAPWossq3EHlGejoFDs4Owvql3A8rGjkInBfTG100Gz4peFuegXXBBb2ia+ecLvHY2RNWtYNy7pFouAFZ0toFBDO0SVsi5HUxXRmAlOMQRMibSSQHvgqQThxvMMgeri0OOA425f300QUgmpmO8V8Ni2wbuFeMWPD/LGDnAB1Rr0ktVl1k1igfJPWr+1k3CkwW6Q3Ifd/axSC47HZiD11pOPGLwVytrk00H715ZcoD0rZmugoK4E8VTZo7VT+TK3No+1RN4NaLEZYtiYgwIDAQABo4GnMIGkMEcGCWCGSAGG+EIBDQQ6FjhGb3IgdGVzdGluZyBvbmx5IGFuZCBubyB0aGlzIGlzIG5vdCB0aGUgcmVhbCB0aGluZy4gRHVoLjALBgNVHQ8EBAMCAQYwHQYDVR0OBBYEFOzeASm6cYYfh+rcadl/5WVaEsCrMB8GA1UdIwQYMBaAFCcbqRTNVaFpFH78kmCwcoXCPZxsMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAB/YWBpT0qEg7KT5De1lsdrVzWAP3UtwhzqQplVyhFYWuxDswOwGYDFxSeoGG62797NPyUuHV3NaeghuFqdLIlYZ03WJTkXnJ3pJmMfU3ZluJZ3PIepXM/WsgFx1rCZrd6985iNThA1cqj+gYni1ZxC9XLtOEyPMRPccQe60lRSbElgp15jhLcuykxXI4IrVDXqoONnUv7YdxiUluYoJeUq9GxF9QaD5iFNh1X0Lvr+6T3soZNSoxlSDmOubJDa78UU2+SPUfI9SuqeXnIRqIc07KPNeL9hMBk+BwqjkI9DphWgA6/4j5OUofnnc+I5ibduFD7ns2befQXfzTu3Z0VYwggNGMIICLqADAgECAgID6DANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAY2IGRlZXAwHhcNMjExMTE3MTIxMTI2WhcNMjIxMTE3MTIxMTI2WjARMQ8wDQYDVQQDDAY3IGRlZXAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSag+/Wt3+67I3pSQw3lzYmSv35/07jc0ZjbdT21uMw/BRIuSRQKGM6puL5wA99aQv2PsFzj45pVcr4UgQalTnbg1iSCxVOaG4kJg3Zh/tEn2NExu8fxNk8VrMpdwI18ymqC245e/xGeO7sqUf9UZkjLKyU183BPQVTDw2xuv4Y56LakfMPEoceavHdUvA+4al6RCSqbZ0OqPddq3x2COSQSD14KvVzLvIBSGxkUnygQ3IOsmqXjiILBdI69QlQI8zYvQdvlcX0OuztGyYbvAwlgiq9LRX2i7c7Y0tJZztmiV9ZMhc4bLS7Lo3oZihUOnvXHdn62XSEIS8sykJ7LvrAgMBAAGjgacwgaQwRwYJYIZIAYb4QgENBDoWOEZvciB0ZXN0aW5nIG9ubHkgYW5kIG5vIHRoaXMgaXMgbm90IHRoZSByZWFsIHRoaW5nLiBEdWguMAsGA1UdDwQEAwIBBjAdBgNVHQ4EFgQUKRo+vQClsD4eL6h3sgRxKx/fXn8wHwYDVR0jBBgwFoAU7N4BKbpxhh+H6txp2X/lZVoSwKswDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAhqn/CUDX1NyrMkVSTGYl6yY7aoSInTVNeR4cFc/S0xxO3mG+q/8+tCEuH+XeOhBkFycDOXC8YZ/Ym+J0U9hE2OW/zQldf9KrcCMq24XpRJ9CJ8HkVpOJjEUDd6imAaZA/G5bFHC6t2jt1j+T6J/VcYzTGppJjG1qdzgcZp13J4VeL7c0Cy9JXQ1TTMa64eNiHIhKrolpk3lKJ69mNKBTUq95+kjUtd4dO3zr/jLgaqfoBeTrtnnnXL9swY5URMhWvtLAKJdk2TkvyCqeC2YwFlT1Z6O2GpRfI3Xadq96lGPTSGZ0Ep5Kbp1Zh2eP8ociv+sWtQXTkQn79BVQX1yelDCCA0YwggIuoAMCAQICAgPoMA0GCSqGSIb3DQEBCwUAMBExDzANBgNVBAMMBjcgZGVlcDAeFw0yMTExMTcxMjExMjZaFw0yMjExMTcxMjExMjZaMBExDzANBgNVBAMMBjggZGVlcDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMJX5rUxXGy5SFW4uaLfvZFlMWAMCrLYDT/i9eM/g3HbM5J+IKesd3EJZX+pu2oEQFcj97VTl3ZVCw57UoIW4KqrNEJrigptVamcaLxrOU1/aZWfqyiDcadLgCU5mi3Hqwo5elgr3HyFp5msEnAg96INU9ys//YZhjlHVQMU6QPza/5+yOPpPQdwYJynLwbWm6cF7AHrRI6CjySn1/HrUvnvGlUXdZklPOZWWHAxDTliwqqvyloImfF/8gM+obL0mq1zn8+Cq0YbmMbFC9MYpdtMPb8us1dEtLIdy2eQYucyyFSZesXVH1f7eD1a9ElqkP9/JUHQ2aRwjX1xFJHf6kcCAwEAAaOBpzCBpDBHBglghkgBhvhCAQ0EOhY4Rm9yIHRlc3Rpbmcgb25seSBhbmQgbm8gdGhpcyBpcyBub3QgdGhlIHJlYWwgdGhpbmcuIER1aC4wCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBQwYC63EgJT6SI70DXYQVL521pJjTAfBgNVHSMEGDAWgBQpGj69AKWwPh4vqHeyBHErH99efzAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBKg2gwuT+eBrrMDrxt+vjnYB8a//I2bAUpWnaXfN4B7RrIHlLMrnHU5l1CHTT70cTrzw2w9leuajNi56VZXD90GWnXhMF9jvk23AhHUKTgqOGyfupLEhJ50azaPju3S/bIaPeQPjlHBIdL1vm/sOPWSm5L7B+JM98pKp0h4aPaoIo7DBA3a7gZAzzYzqaBFpfgPVkr7oBG89ETh7v1UctB2cf2jtf+nTZvKqnT29IZ+bqAumt8l+cw84p/z52TdQuN45zWyOiWMajtOsXmVqwjaVhfeFHVJkuol8/5tHSnHZC4mbgMpFawO/z4oCnS/U7R63DqFFYtOgNLcge1mSL/MIIDRjCCAi6gAwIBAgICA+gwDQYJKoZIhvcNAQELBQAwETEPMA0GA1UEAwwGOCBkZWVwMB4XDTIxMTExNzEyMTEyNloXDTIyMTExNzEyMTEyNlowETEPMA0GA1UEAwwGOSBkZWVwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+K1AeTYLCkdf64vG37BhNJe1eHTA1x5CvVckdDDO2TMnIyiLLudZcsGyohAE4Etd6Iy3Vy8oKikwLzvo2mXd0I5qJrVxDZnI19xIXjBBREH0uDhShWP9sx0cUYKzp4+AesZtL/79PEoLnK5aJ1IXfcD8RXE7YCCEsUF6SbQPmTTDF2K6HDZAQGarCCdA5ZcTQoLqg75gmW/OY6sfJwOIAlXOGMiTbPCuHeAmxUPsaPgemeIis0771hz/KYWoXncquBbsI3Ke/pzk7MT5PdwICQui1llT6iM+hUuA8RunzY3uaunRx4vLg+we2LcmZkpYKhiF+fgYIV06F277NSK9LwIDAQABo4GnMIGkMEcGCWCGSAGG+EIBDQQ6FjhGb3IgdGVzdGluZyBvbmx5IGFuZCBubyB0aGlzIGlzIG5vdCB0aGUgcmVhbCB0aGluZy4gRHVoLjALBgNVHQ8EBAMCAQYwHQYDVR0OBBYEFKeNICSh/kdVbiq17WQgMki7HPRFMB8GA1UdIwQYMBaAFDBgLrcSAlPpIjvQNdhBUvnbWkmNMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHh3bvqoFXe2e5fdUaF3nKSBi+g6v8rNv0LmyCkISU9K8aplKQUmka6q3GarKUqU9lE6VhAfyBeK3E2LSuaI5fmn5FTYtMp1ethJkuqXtknptpW1C0qvcw9juhEbkgB9s+tYW+T+mMxA96oB1TAaqHj0INxk+c4ZKvjuErLqZ8u9l9AF2cxUfIYXlXvdmp3QJRXQ6v7o8MGlE9wGnPfMMmrDlxEgO4H0cPuuUpJss2AolqRNKdoyhOj4o0e7lC4MIyS38hE83o09DpayR1PD8hC7BuXJAcI2zjXFIzxsAXDHjI/DK9vfddiloM2lxHwNoHb/u9WIJlfNRiF1eFJPOVQwggNKMIICMqADAgECAgsA3q2+796tvu/A3jANBgkqhkiG9w0BAQsFADARMQ8wDQYDVQQDDAY5IGRlZXAwHhcNMjExMTE3MTIxMTI3WhcNMjIxMTE3MTIxMTI3WjAPMQ0wCwYDVQQDDARsZWFmMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnao8yprTuk/HECuC7FE1SJnrtjheZvu4N9Zc93YYCpJQokGHMTgnsiKASLMU7n9HhvgcGVSyKB384jccwOSgeeSfIv/vipBLRPk6mAFJZk2LlmHdomLmAy/NWbxF9wTy/yVAsUx5i2jblqzXgXH9sT6m/Oo4p/ON8LQ+egfqcHACwCffsCV6zzT7xCVHpDL9VdnTxTV6QFK6HbqvEUL12k+WaZhyMV32ikIVeoY1C2/INd63Shsslq0c9FSbJwHECUaGlkWvFBCzyzYozS4ibMLvpjGxyj38eip/JIGYMtVQP7Ln8zSfKKc7dowCzngYLZQ4fTNNcRCXo/hOomu+ZwIDAQABo4GkMIGhMEcGCWCGSAGG+EIBDQQ6FjhGb3IgdGVzdGluZyBvbmx5IGFuZCBubyB0aGlzIGlzIG5vdCB0aGUgcmVhbCB0aGluZy4gRHVoLjALBgNVHQ8EBAMCBeAwHQYDVR0OBBYEFH9ES1NdDtpFwmUnNOXg9tEH+fPwMB8GA1UdIwQYMBaAFKeNICSh/kdVbiq17WQgMki7HPRFMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBAIy7e3qYO6fbGvc6+scnEqASqC3iLs5J0qCHvU4AAz3IjW2Li6djltwYktIEbxG/ExytqGi3U/viu952ZLAcLOgxpNxl5WfVbLD2alHnMHvBTfCkzDjqeL7gmuIZLq2j3jnOp1p9UZsoKyhZ9S60PHDgDQ4im5GlGvotFWS1fian/yf5q/FX8r++vVEfpaxKa62idBk+9zaIs5vSJop946pkVr8VjtswHteU75YCpwjLOpRdnqqjuUmmPNxjWTKZ7mFoBlCKf9TkEBkRIjDedh6qI3g9skzzmMqT6SmA4y0s7vCLKABowOH3UGi226TIEAqM8owMBKC2LDuEqQqAT3QxggJhMIICXQIBATAgMBExDzANBgNVBAMMBjkgZGVlcAILAN6tvu/erb7vwN4wCwYJYIZIAWUDBAIBoIHkMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIxMTExNzEyMTEyN1owLwYJKoZIhvcNAQkEMSIEII3qIngl0AG+hRtZnqHqM+YCKd64tyzB5USxq4OsmlFNMHkGCSqGSIb3DQEJDzFsMGowCwYJYIZIAWUDBAEqMAsGCWCGSAFlAwQBFjALBglghkgBZQMEAQIwCgYIKoZIhvcNAwcwDgYIKoZIhvcNAwICAgCAMA0GCCqGSIb3DQMCAgFAMAcGBSsOAwIHMA0GCCqGSIb3DQMCAgEoMD4GCSqGSIb3DQEBCjAxoA0wCwYJYIZIAWUDBAIBoRowGAYJKoZIhvcNAQEIMAsGCWCGSAFlAwQCAaIEAgIA3gSCAQBM2F7WEQJEcEVzWpQnaqXjtCqUa1aduFu/+Y3BlEFCeUodLU3a1mcbBtr5Kl8ye1Bwfb8hbKy8HEP7QnjMkosXfi/fS27d7IeSAKAP3Tzvib+WvzbrojptmppRsAJW828q78LZ06dQ6NtJJZf8xXBhz+pKo+5kzWfkbVjeEA14X9//275XycXyOY4xw8AoGX4ebkXySFALiW7Lab3VaCFOs5gfXb8C0ogZ+1gosVbhooYT5GS9qvVOPAgjGfhPZLA2NeZjQu/FHNnZxW3Sc7/9WaEMDgx2B9nMr2DOcyTJgoQmG+Sz3IVGi9tqIGS9Sqw29Rqt87TTYDFLRO6YZHWg")!

	// MARK: - Signature

	// Install openssl: brew install openssl@1.1
	// Use Scripts/ssl/generate/generate.sh to generate the certFakePKIOverheid certificate
	// zsh generate/generate.sh
	// Move the files
	// cp generate/ca.pem ../certFakePKIOverheid.pem
	// cp certFakePKIOverheid.pem ../../CTRTests/Infrastrucure/Crypto/Utility/files/certFakePKIOverheid.pem
	// cp generate/chain.pem ../chain.pem
	// cp generate/client.crt ../client.crt
	//
	// Use Scripts/ssl/sign.sh example.json to generate the pkci signature (zsh sign.sh example.json)
	// copy the signature to line 36 of this file: signaturePKCS
	//
	// Use Scripts/ssl/sign_pss.sh example.json to generate the pss signature (zsh sign_pps.sh example.json)
	// copy the signature to line 39 of this file: signaturePSS
	//
	// set a breakpoint in openssl.m, line 217
	// enable #define DEBUG in openssl.m, line 24
	// when breakpoints hits: po print_octed_as_hex(authorityKeyIdentifier)
	// copy the key to line 25 of this file in authorityKeyIdentifier.
	// disable the #define DEBUG in openssl.m, line 24
	
	func testCMSSignature_padding_pkcs_validPayload() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl"
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_padding_pkcs_wrongPayload() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: wrongPayload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl"
		)

		// Then
		expect(validation) == false
	}

	func testCMSSignature_padding_pss_validPayload() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePSS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl"
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_padding_pss_wrongPayload() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			wrongPayload,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl"
		)

		// Then
		expect(validation) == false
	}

	func testCMSSignature_test_pinning_wrongCommonName() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronacheck.nl"
		)

		// Then
		expect(validation) == false
	}

	func testCMSSignature_test_pinning_commonNameAsPartOfDomain() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl.xx.nl"
		)

		// Then
		expect(validation) == false
	}

	func testCMSSignature_test_pinning_emptyCommonName() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ""
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_test_pinning_emptyAuthorityKeyIdentifier() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: nil,
			requiredCommonNameContent: "coronatester.nl"
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_test_pinning_emptyAuthorityKeyIdentifier_emptyCommonName() throws {

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certFakePKIOverheid", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signaturePKCS,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: nil,
			requiredCommonNameContent: ""
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_verydeep() throws {

		// Use long-chain.sh to generate this certificate (0.pem -> certDeepChain.pem)

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certDeepChain", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			deepSignature,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: deepAuthorityKeyIdentifier,
			requiredCommonNameContent: "leaf"
		)

		// Then
		expect(validation) == true
	}

	func testCMSSignature_invalidAuthorityKeyIdentifier() throws {

		// Use long-chain.sh to generate this certificate

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certDeepChain", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			deepSignature,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: authorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester.nl"
		)

		// Then
		expect(validation) == false
	}

	func testCMSSignature_noCommonName() throws {

		// Use long-chain.sh to generate this certificate

		// Given
		let certificateUrl = try XCTUnwrap(testBundle.url(forResource: "certWithoutCN", withExtension: ".pem"))
		let certificateData = try Data(contentsOf: certificateUrl)

		// When
		let validation = sut.validatePKCS7Signature(
			signatureNoCommonName,
			contentData: payload,
			certificateData: certificateData,
			authorityKeyIdentifier: noCommonNameAuthorityKeyIdentifier,
			requiredCommonNameContent: ".coronatester..nl"
		)

		// Then
		expect(validation) == false
	}
}
