direction: down

# Third-Party
Rswift: {
  shape: hexagon
}
Reachability: {
  shape: hexagon
}
BrightFutures: {
  shape: hexagon
}
HTTPSecurity: {
  shape: hexagon
}
LuhnCheck: {
  shape: hexagon
}
iOSSecuritySuite: {
  shape: hexagon
}
Lottie: {
  shape: hexagon
}
QRGenerator: {
  shape: hexagon
}
OpenIDConnect: {
  shape: hexagon
}
SwiftSoup: {
  shape: hexagon
}
GZip: {
  shape: hexagon
}

# The application

app: {
  shape: package
}

app <- BrightFutures
app <- CryptoCore
app <- DataMigration
app <- Lottie
app <- Managers
app <- Models
app <- OpenIDConnect
app <- Persistence
app <- QRGenerator
app <- Reachability
app <- RestrictedBrowser
app <- Reusableviews
app <- Shared
app <- Transport

# - Packages - 

CryptoCore { style.fill: "#ffcc00" }

DataMigration { style.fill: "#ffcc00" }
DataMigration <- Shared
DataMigration <- GZip

Managers { style.fill: "#ffcc00" }
Managers <- CryptoCore
Managers <- Models
Managers <- Persistence
Managers <- Resources
Managers <- Shared
Managers <- Transport
Managers <- BrightFutures
Managers <- iOSSecuritySuite

Models { style.fill: "#ffcc00" }
Models <- CryptoCore
Models <- Persistence
Models <- Shared
Models <- Transport
Models <- LuhnCheck

Persistence { style.fill: "#ffcc00" }
Persistence <- Shared

Resources { style.fill: "#ffcc00" }
Resources <- Shared
Resources <- Rswift

RestrictedBrowser { style.fill: "#ffcc00" }
RestrictedBrowser <- Shared
RestrictedBrowser <- Resources
RestrictedBrowser <- ReusableViews

ReusableViews { style.fill: "#ffcc00" }
ReusableViews <- Shared
ReusableViews <- Resources

Shared { style.fill: "#ffcc00" }
Shared <- Reachability
Shared <- SwiftSoup

Transport { style.fill: "#ffcc00" }
Transport <- HTTPSecurity
Transport <- Shared