name: 'Build mobile core'
description: 'Builds the mobile core library'
inputs:
  mobile_core_commit_hash:
    type: string
    required: true
  go_version:
    type: string
    required: false
    default: '1.20.5'
  temp_path:
    type: string
    required: false
    default: 'tmp-mobile-core'
  destination_path:
    type: string
    required: false
    default: 'Packages/CryptoCore/Frameworks/mobilecore.xcframework'

runs:
  using: "composite"
  steps:
    - name: Checkout Mobile Core
      shell: bash
      run: |
        set -eux
        git clone https://github.com/minvws/nl-covid19-coronacheck-mobile-core.git "${{ inputs.temp_path }}"
        cd "${{ inputs.temp_path }}"
        git checkout ${{ inputs.mobile_core_commit_hash }}

    - name: Restore mobilecore.framework from cache
      id: cachestep
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.destination_path }}
        key: mobilecore-xcframework-${{ inputs.mobile_core_commit_hash }}-${{ inputs.go_version }}-v3

    - name: Setup Go
      if: steps.cachestep.outputs.cache-hit != 'true'
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # pin@v4
      with:
        go-version: '${{ inputs.go_version }}'
        cache-dependency-path: '${{ inputs.temp_path }}/go.sum'
      
    - name: Compile Go library dependency
      if: steps.cachestep.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -eux

        pushd "${{ inputs.temp_path }}"
        go mod download golang.org/x/mobile
        go install golang.org/x/mobile/cmd/gomobile@latest
        gomobile init
        gomobile bind -target ios,iossimulator -o mobilecore.xcframework -iosversion 11.0 github.com/minvws/nl-covid19-coronacheck-mobile-core
        popd

        rm -rf mobilecore.framework Frameworks # TODO: I don't think these are necessary
        rm -rf "${{ inputs.destination_path }}"
        cp -r "${{ inputs.temp_path }}/mobilecore.xcframework" "${{ inputs.destination_path }}"
        rm -rf "${{ inputs.temp_path }}"

    - name: Save mobile core to cache
      if: steps.cachestep.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: |
          ${{ inputs.destination_path }}
        key: mobilecore-xcframework-${{ inputs.mobile_core_commit_hash }}-${{ inputs.go_version }}-v3
