name: sigrid-publish
on:
  push:
    branches:
      - "main"
jobs:
  sigridci:
    if: github.event.repository.name == 'nl-covid19-coronacheck-app-ios-private'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
      - name: "Run Sigrid CI"
        env:
          SIGRID_CI_ACCOUNT: "${{ secrets.SIGRID_CI_ACCOUNT }}"
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
        run: "./sigridci/sigridci/sigridci.py --customer vws --system coronacheck-ios --source . --targetquality 3.0 --publish"
