# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: firebase-deploy-template

on:
  workflow_call:
    inputs:
      fastlane_command:
        required: true
        type: string
      app_title:
        required: true
        type: string
      app_filename:
        required: true
        type: string
    secrets:
      DIST_CERT_CONTENTS:
        required: true
      DIST_CERT_PASSWORD:
        required: true
      FIREBASE_TOKEN:
        required: true
      SLACK_URL:
        required: true

env: 
  DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10

jobs:
  template_firebase-deploy:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   
    
    - name: Log Build Number
      run: |
        ./Scripts/log-build-number.sh

    - name: Load certificate
      env:
        CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
      run: |
        mkdir fastlane/certificates
        echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup CI environment
      run: |
        make ci
    
    - name: Setup Imagemagick for icon overlays
      run: |
        make homebrew_ci_imagemagick

    - name: Build and deploy
      timeout-minutes: 45
      env:
        CERTIFICATE_PATH: fastlane/certificates/distribution.p12
        CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SLACK_URL: ${{ secrets.SLACK_URL }}
        GITBRANCH: ${{ github.ref }}
      run: |
        ${{ inputs.fastlane_command }}

    - name: Archive App
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.app_title }}
        path: ${{ inputs.app_filename }}.ipa
        retention-days: 10

    - name: Archive dSYMs
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.app_title }} dSYMs
        path: ${{ inputs.app_filename }}.app.dSYM.zip
        retention-days: 10


