# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: testflight

on:
  push:
    tags:
      - 'Verifier-*.*.*-RC*'
      - 'Holder-*.*.*-RC*'
  workflow_dispatch:

env: 
  APPSTORE_KEY_BASE64_FILENAME: appstore-apikey.p8
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10

jobs:
  upload:
    if: github.event.repository.name == 'nl-covid19-coronacheck-app-ios-private'
    runs-on: macos-11
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log Build Number
        run: |
          ./Scripts/log-build-number.sh
                    
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup CI environment
        run: |
          make ci
                
      - name: Write p8 Key
        if: github.event.repository.name == 'nl-covid19-coronacheck-app-ios-private'
        env:
          APP_STORE_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_API_KEY_P8 }}
        run: | 
          echo $APP_STORE_API_KEY_P8_BASE64 | base64 --decode > $APPSTORE_KEY_BASE64_FILENAME # not certain this is p8 format
          
      - name: Load certificate
        env:
          CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
        run: |
          mkdir fastlane/certificates
          echo "$CERTIFICATE_CONTENTS" | base64 -D > fastlane/certificates/distribution.p12          

      - name: Ship Holder to TestFlight
        if: ${{ !contains(github.ref, 'Verifier') }}
        timeout-minutes: 120
        env:
          CERTIFICATE_PATH: fastlane/certificates/distribution.p12
          CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_URL }}      
          APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
          APP_STORE_API_KEY_ISSUER: ${{ secrets.APP_STORE_API_KEY_ISSUER }}
        run: |
          bundle exec fastlane ios ship_holder_to_testflight

      - name: Archive Holder
        if: ${{ !contains(github.ref, 'Verifier') }}
        uses: actions/upload-artifact@v2
        with:
          name: Holder App
          path: CTR.ipa
          retention-days: 30

      - name: Archive Holder dSYMs
        if: ${{ !contains(github.ref, 'Verifier') }}
        uses: actions/upload-artifact@v2
        with:
          name: Holder App dSYMs
          path: CTR.app.dSYM.zip
          retention-days: 30

      - name: Ship Verifier to TestFlight
        if: ${{ !contains(github.ref, 'Holder') }}
        timeout-minutes: 120
        env:
          CERTIFICATE_PATH: fastlane/certificates/distribution.p12
          CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_URL }}      
          APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
          APP_STORE_API_KEY_ISSUER: ${{ secrets.APP_STORE_API_KEY_ISSUER }}
        run: |
          bundle exec fastlane ios ship_verifier_to_testflight

      - name: Archive Verifier
        if: ${{ !contains(github.ref, 'Holder') }}
        uses: actions/upload-artifact@v2
        with:
          name: Verifier App
          path: Verifier.ipa
          retention-days: 30

      - name: Archive Verifier dSYMs
        if: ${{ !contains(github.ref, 'Holder') }}
        uses: actions/upload-artifact@v2
        with:
          name: Verifier App dSYMs
          path: Verifier.app.dSYM.zip
          retention-days: 30
