// Objective-C API for talking to github.com/minvws/nl-covid19-coronacheck-cl-core/clmobile Go package.
//   gobind -lang=objc github.com/minvws/nl-covid19-coronacheck-cl-core/clmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Clmobile_H__
#define __Clmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class ClmobileAnnotatedPk;
@class ClmobileResult;
@class ClmobileVerifyResult;

@interface ClmobileAnnotatedPk : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSData* _Nullable pkXml;
@end

@interface ClmobileResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable value;
@property (nonatomic) NSString* _Nonnull error;
@end

@interface ClmobileVerifyResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable attributesJson;
@property (nonatomic) int64_t unixTimeSeconds;
@property (nonatomic) NSString* _Nonnull error;
@end

@interface Clmobile : NSObject
+ (BOOL) hasLoadedIssuerPks;
+ (void) setHasLoadedIssuerPks:(BOOL)v;

@end

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileCreateCommitmentMessage(NSData* _Nullable holderSkJson, NSData* _Nullable issuerNonceMessageBase64);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileCreateCredential(NSData* _Nullable holderSkJson, NSData* _Nullable ccmJson);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileDiscloseAllWithTime(NSData* _Nullable credJson);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileDiscloseAllWithTimeQrEncoded(NSData* _Nullable holderSkJson, NSData* _Nullable credJson);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileGenerateHolderSk(void);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileLoadIssuerPks(NSData* _Nullable annotatedPksJson);

FOUNDATION_EXPORT ClmobileResult* _Nullable ClmobileReadCredential(NSData* _Nullable credJson);

FOUNDATION_EXPORT ClmobileVerifyResult* _Nullable ClmobileVerify(NSData* _Nullable proofAsn1);

FOUNDATION_EXPORT ClmobileVerifyResult* _Nullable ClmobileVerifyQREncoded(NSData* _Nullable proofQrEncodedAsn1);

#endif
