// Objective-C API for talking to github.com/minvws/nl-covid19-coronacheck-mobile-core Go package.
//   gobind -lang=objc github.com/minvws/nl-covid19-coronacheck-mobile-core
//
// File is generated by gobind. Do not edit.

#ifndef __Mobilecore_H__
#define __Mobilecore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobilecoreAnnotatedDomesticPk;
@class MobilecoreAnnotatedEuropeanPk;
@class MobilecoreCreateCredentialResultValue;
@class MobilecorePublicKeysConfig;
@class MobilecoreResult;
@class MobilecoreVerificationResult;

@interface MobilecoreAnnotatedDomesticPk : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable pkXml;
// skipped field AnnotatedDomesticPk.LoadedPk with unsupported type: *github.com/privacybydesign/gabi.PublicKey

/**
 * DEPRECATED: Remove this field together with LegacyDomesticPks
 */
@property (nonatomic) NSString* _Nonnull kid;
@end

@interface MobilecoreAnnotatedEuropeanPk : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable subjectPk;
// skipped field AnnotatedEuropeanPk.KeyUsage with unsupported type: []string

// skipped field AnnotatedEuropeanPk.LoadedPk with unsupported type: interface{}

@end

@interface MobilecoreCreateCredentialResultValue : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field CreateCredentialResultValue.Credential with unsupported type: *github.com/privacybydesign/gabi.Credential

// skipped field CreateCredentialResultValue.Attributes with unsupported type: map[string]string

@end

@interface MobilecorePublicKeysConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)pksPath expectEuropeanKeys:(BOOL)expectEuropeanKeys;
// skipped field PublicKeysConfig.DomesticPks with unsupported type: github.com/minvws/nl-covid19-coronacheck-mobile-core.DomesticPksLookup

// skipped field PublicKeysConfig.EuropeanPks with unsupported type: github.com/minvws/nl-covid19-coronacheck-mobile-core.EuropeanPksLookup

// skipped field PublicKeysConfig.LegacyDomesticPks with unsupported type: []*github.com/minvws/nl-covid19-coronacheck-mobile-core.AnnotatedDomesticPk

// skipped method PublicKeysConfig.FindAndCacheDomestic with unsupported parameter or return types

// skipped method PublicKeysConfig.FindAndCacheEuropean with unsupported parameter or return types

/**
 * DEPRECATED: Remove this legacy transformation together with LegacyDomesticPks
 */
- (void)transformLegacyDomesticPks;
@end

@interface MobilecoreResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable value;
@property (nonatomic) NSString* _Nonnull error;
@end

/**
 * VerificationResult very much mimics the domestic verifier attributes, with only string type values,
 to minimize app-side changes. In the future, both should return properly typed values.
 */
@interface MobilecoreVerificationResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull credentialVersion;
@property (nonatomic) NSString* _Nonnull isSpecimen;
@property (nonatomic) NSString* _Nonnull firstNameInitial;
@property (nonatomic) NSString* _Nonnull lastNameInitial;
@property (nonatomic) NSString* _Nonnull birthDay;
@property (nonatomic) NSString* _Nonnull birthMonth;
@property (nonatomic) NSString* _Nonnull isNLDCC;
@end

FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreHOLDER_CONFIG_FILENAME;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreHOLDER_PUBLIC_KEYS_FILENAME;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreV1_VALIDITY_HOURS_STR;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreVERIFIER_CONFIG_FILENAME;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreVERIFIER_PUBLIC_KEYS_FILENAME;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreYYYYMMDD_FORMAT;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreYYYYMM_FORMAT;
FOUNDATION_EXPORT NSString* _Nonnull const MobilecoreYYYY_FORMAT;

@interface Mobilecore : NSObject
/**
 * These constants can be moved to the verifier configuration file in the future
 */
+ (NSString* _Nonnull) diseasE_TARGETED_COVID_19;
+ (void) setDISEASE_TARGETED_COVID_19:(NSString* _Nonnull)v;

/**
 * These constants can be moved to the verifier configuration file in the future
 */
+ (int64_t) hcerT_SPECIMEN_EXPIRATION_TIME;
+ (void) setHCERT_SPECIMEN_EXPIRATION_TIME:(int64_t)v;

/**
 * DEPRECATED: See deprecation of LoadDomesticIssuerPks
 */
+ (BOOL) hasLoadedDomesticIssuerPks;
+ (void) setHasLoadedDomesticIssuerPks:(BOOL)v;

/**
 * These constants can be moved to the verifier configuration file in the future
 */
+ (NSString* _Nonnull) tesT_RESULT_NOT_DETECTED;
+ (void) setTEST_RESULT_NOT_DETECTED:(NSString* _Nonnull)v;

@end

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreCreateCommitmentMessage(NSData* _Nullable holderSkJson, NSData* _Nullable prepareIssueMessageJson);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreCreateCredentials(NSData* _Nullable ccmsJson);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreDisclose(NSData* _Nullable holderSkJson, NSData* _Nullable credJson);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreErrorResult(NSError* _Nullable err);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreGenerateHolderSk(void);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreInitializeHolder(NSString* _Nullable configDirectoryPath);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreInitializeVerifier(NSString* _Nullable configDirectoryPath);

/**
 * DEPRECATED: Remove this method when the mobile apps have migrated to using
 InitializeHolder and the holder package directly
 */
FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreLoadDomesticIssuerPks(NSData* _Nullable annotatedPksJson);

FOUNDATION_EXPORT MobilecorePublicKeysConfig* _Nullable MobilecoreNewPublicKeysConfig(NSString* _Nullable pksPath, BOOL expectEuropeanKeys, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreReadDomesticCredential(NSData* _Nullable credJson);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreReadEuropeanCredential(NSData* _Nullable proofPrefixed);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreVerify(NSData* _Nullable proofQREncoded);

FOUNDATION_EXPORT MobilecoreResult* _Nullable MobilecoreWrappedErrorResult(NSError* _Nullable err, NSString* _Nullable prefix);

#endif
